### ISSUE TITLE
`session` hash is erased on create, update, and destroy

### ISSUE THREAD

**Issue by alexeymuranov** [cjbottaro/param_protected#11]
I do not know if this is expected, i haven't found this documented, and do not know how to get around.

If i add `param_accessible` to my controller, all custom entries of `session` are erased on POST, PUT, and DELETE requests.

Here are steps to reproduce:

``` shell
rails new test_param_protect
cd test_param_protect/
echo "gem 'param_protected'" >> Gemfile
bundle install
rails generate scaffold User name:string
rake db:migrate
rails generate controller SessionWriter write_a_value
```

In **session_writer_controller.rb**:

``` ruby
def write_a_value
  session[:test_key] = 'TestValue'
end
```

In **application.html.erb**:

``` erb
<body>
  <%= yield %>
  <%= debug(params) %>
  <%= debug(session.to_hash) %>
</body>
```

In **users_controller.rb**:

``` ruby
# XXX: This erases `session` hash on create, update, and destroy:
param_accessible [ 'id', { 'user' => [ 'name' ] }]
```

Then run `rails server` and visit [localhost:3000/session_writer/write_a_value](http://localhost:3000/session_writer/write_a_value) and [localhost:3000/users/](http://localhost:3000/users/), and see what happens to `session` when creating, updating, or deleting users.

**Comment by cjbottaro** [comment]
What version of Rails and param_protected are you using?

**Comment by alexeymuranov** [comment]
This is with rails (3.2.2) and param_protected (4.0.0).

**Comment by cjbottaro** [comment]
Ok, I can reproduce the problem with your steps.  Will look into it today.  Thanks for the report.

**Comment by cjbottaro** [comment]
Add `authenticity_token` to your whitelist.

``` ruby
param_accessible [ 'id', 'authenticity_token', { 'user' => [ 'name' ] }]
```

I think there is an open ticket for a default list of params that should always be whitelisted (action, controller, authenticity_token, etc).

I think people usually put the following in their `application_controller.rb`:

``` ruby
  param_accessible [ 'controller', 'action', 'authenticity_token' ]
```

**Comment by alexeymuranov** [comment]
Ah, i see, thank you!

**Comment by alexeymuranov** [comment]
However, i do not understand: why does the `session` get erased?

**Comment by cjbottaro** [comment]
I don't know why either.  Im guessing that it's some cross site scripting security measure built into Rails.  Like if a form is submitted without the CSRF token, then your session gets erased.

I see this in my logs:

```
WARNING: Can't verify CSRF token authenticity
```

When param_protected removes the `authenticity_token` param.

**Comment by alexeymuranov** [comment]
Ok, thanks.
