### ISSUE TITLE
incompatible with rails 3.1

### ISSUE THREAD

**Issue by gucki** [cjbottaro/param_protected#7]
Just adding the gem (2.0.0) to the Gemfile is enough to completely break the app.

Different exceptions show up, like

```
ActionView::Template::Error in SessionsController#new
undefined local variable or method `session_path' for #<#<Class:0x000000055708c8>:0x00000003c427e8>
```

or

```
ActionView::Template::Error in PagesController#show
In order to use #url_for, you must include routing helpers explicitly. For instance, `include Rails.application.routes.url_helpers
```

**Comment by cjbottaro** [comment]
Yikes... ok.  I'll try to get to it soon.  It might be a while though.  Very busy lately.

**Comment by gucki** [comment]
Pull request is here now: https://github.com/cjbottaro/param_protected/pull/8
