### ISSUE TITLE
Default whitelist params

### ISSUE THREAD

**Issue by zlw** [cjbottaro/param_protected#9]
Hi,

I think that some params should be in whitelist by default:

``` ruby
param_accessible [:utf8, :commit, :action, :controller, :id]

# or maybe even
param_accessible [:utf8, :commit, :action, :controller, :id, :authenticity_token, :page]
```

:authenticity_token is from devise
:page is used by kaminari/will_paginate (both are common used gems)

**Comment by zlw** [comment]
Oh, I see it's copy of issue #1.

Sorry

**Comment by cjbottaro** [comment]
Yikes, sorry this email got buried and I forgot about it.  I'm actually out of town on business, but I'll try to look at the issue when I get back home. 

Thanks,
-- C
